name: Main

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci_main.yaml'
      - 'go.mod'
      - 'pretty.go'
      - 'pretty_test.go'
  pull_request:
    branches:
      - main

env:
  GOLANG_CI_LINT_VERSION: v1.48.0

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [1.17.x, 1.18.x, 1.19.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}
          args: --timeout=5m

      - name: Test
        run: go test -v .

      - name: Build
        run: go build -v .
