name: CI@main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GOLANG_CI_LINT_VERSION: v1.47.0

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test
        run: go test -v .

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: [1.16.x, 1.17.x, 1.18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: go build -v .
